### ISSUE TITLE
custom_fields support for Ticket

### ISSUE THREAD

**Issue by nukosuke** [nukosuke/go-zendesk#122]
https://developer.zendesk.com/rest_api/docs/support/tickets#setting-custom-field-values

**Comment by tamccall** [comment]
do we need to do anything for this other than make a type custom field that is a struct containing an ID integer and value of interface.

```go
type CustomField struct {
	ID int64
	Value interface{}
}
```

I've been trying to think of a better way to handle it but i can't seem come up with anything that seems preferable to that. Let me know if you have an opinion on the topic.

**Comment by nukosuke** [comment]
#142 was merged
