### ISSUE TITLE
via field support for ticket

### ISSUE THREAD

**Issue by nukosuke** [nukosuke/go-zendesk#123]
https://developer.zendesk.com/rest_api/docs/support/ticket_audits.html#the-via-object

**Comment by tamccall** [comment]
How about something like this for the via object.
```go
type Via struct {
	Channel string
	From map[string]interface{}
	To map[string]interface{}
	Rel string
}
```

**Comment by abebars** [comment]
@nukosuke are fine with this structure that @tamccall posted? I was looking to get a PR for that. I think this structure makes sense what do you think?

**Comment by nukosuke** [comment]
Via support has been released. Thank you!
https://github.com/nukosuke/go-zendesk/releases/tag/v0.7.4
