### ISSUE TITLE
Add Search API Support

### ISSUE THREAD

**Issue by mattroark** [nukosuke/go-zendesk#134]
https://developer.zendesk.com/rest_api/docs/support/search

**Comment by tamccall** [comment]
what do we think the client interface would look like for this?

I could see something like this
```go
type Query struct {
  Query string
  SortOrder string
  SortBy string
  Page int  
}

type SearchAPI interface {
	Search(ctx context.Context, query String) (Results, error)
}
```

I see a couple of issues with that just curious what people think about it.

- getting the next page of data will be a bit cumbersome bc we will not be able to directly use the next page field in the result
- building the query string might be a bit messy as well.

Curious if anyone else has any better ideas on the method signature.

**Comment by tamccall** [comment]
probably should try and mimic this.

https://github.com/nukosuke/go-zendesk/blob/master/zendesk/ticket.go#L112-L125

**Comment by tamccall** [comment]
@mattroark I've opened up https://github.com/nukosuke/go-zendesk/pull/151 to address this.

Would love any feedback that you have on the pr.

**Comment by Senpos** [comment]
Since it is merged already, I tried the "Search" functionality and it works fine for me :)

**Comment by nukosuke** [comment]
Thank you guys.

Then i'd like to close this. Please open new issue if you would have any trouble with this feature.
