### ISSUE TITLE
Client.prepareRequest does not actually set a context

### ISSUE THREAD

**Issue by jcbwlkr** [nukosuke/go-zendesk#155]
In these lines https://github.com/nukosuke/go-zendesk/blob/8f6e34bf8749562b0436f91389188d521c521999/zendesk/zendesk.go#L213-L214

It is not affecting the context of the request in the outer function. All that is happening here is  the pointer variable `req` in the function is being replaced with a pointer to a new request. The other things like setting headers happen to work because the header fields are still pointing to the same map structure.

To see what I mean run this https://play.golang.org/p/H3NN_RY7VMs It prints `<nil>` because it does not see the new context on the request. If you uncomment line 23 and run it again you will see the context is set now.

One solution is to change line 214 to

```
*req = *(req.WithContext(ctx))
```

**Comment by tamccall** [comment]
I believe this should be fixed as part of https://github.com/nukosuke/go-zendesk/releases/tag/v0.7.1
