### ISSUE TITLE
Add support for "webhooks"

### ISSUE THREAD

**Issue by pypypyo14** [nukosuke/go-zendesk#211]
HTTP target will be deprecated on Feb 2022 and conversion to new feature "webhooks".

I would be grateful if go-zendesk would support webhooks.

Doc about deprecation:
https://support.zendesk.com/hc/en-us/articles/4408826284698

API referrence:
https://developer.zendesk.com/api-reference/event-connectors/webhooks/webhooks/

**Comment by nukosuke** [comment]
webhook API would be suported at the coming version.
thx for reporting!
