### ISSUE TITLE
mock client

### ISSUE THREAD

**Issue by nukosuke** [nukosuke/go-zendesk#34]
interface for zendesk.Client

It’s useful for testing application which uses this library.

**Comment by tamccall** [comment]
I can take a stab at this

**Comment by tamccall** [comment]
which mocking library would you rather use?

I assume https://github.com/golang/mock, but i have used https://github.com/stretchr/testify#mock-package before as well.

**Comment by nukosuke** [comment]
Although I have seen them I don't really know much about them.

Which would you prefer?
I'll take your advice.

**Comment by tamccall** [comment]
i went with golang/mock.

have pr up here.

https://github.com/nukosuke/go-zendesk/pull/56/

**Comment by nukosuke** [comment]
Thanks.
I'll check it later.

**Comment by nukosuke** [comment]
Resolved at #56
