### ISSUE TITLE
Add support for attachment upload

### ISSUE THREAD

**Issue by nukosuke** [nukosuke/go-zendesk#63]
https://developer.zendesk.com/rest_api/docs/support/attachments
This is a little bit complicated issue. `Attachment` is child element of `User` and `Brand`. But, their API has no ability to add the data to JSON payload directly because it can be binary like a picture.

Attachment API accepts `application/binary` and response metadata of uploaded data as Attachment schema. Then, we should use this response as `User` and `Brand`'s request payload.

---
Attachment field is optional. So, no need to work on this soon.

**Comment by tamccall** [comment]
I wonder if we could mimic what the [google cloud api sdk does for its storage api](https://cloud.google.com/storage/docs/uploading-objects#storage-upload-object-code_sample).

Basically what it does is returns this [handler object](https://godoc.org/cloud.google.com/go/storage#ObjectHandle) that you can use to write the file up.


maybe it would look something like this...
```go
// some reader r
w :=  client.UploadAttachment("filename").SetToken("token").Writer()
ioutil.Copy(w, r)
```
