### ISSUE TITLE
Add go context to all client methods.

### ISSUE THREAD

**Issue by tamccall** [nukosuke/go-zendesk#70]
Need to add the [go context](https://golang.org/pkg/context/#Context) to all of the Exported client methods to allow clients to set deadlines when calling zendesk.

**Comment by u5surf** [comment]
@tamccall 
I think you are concerned about if zendesk api server returned response in high latency, it would come to block the other procedure. so, It's should be implemented timeout context to prevent blocking.

 I think it shold only implemented http request methods(Get, Post, Put, Delete) instead of all Exported one. I tried to implement WithTimeout context to several methods which use `net/http.Request`

**Comment by tamccall** [comment]
@u5surf i had some comments in your pr about this. I am not sure if going for an arbitrary 1 second deadline for these requests is the best way to go about this. IMO it is better to let the client define that.

**Comment by tamccall** [comment]
@nukosuke do we want to do this update api by api or should we try to handle it all at once.

Api by api would make things easier to review, but will require more version updates / there will be a period when the not all of the APIs will match each other.

**Comment by tamccall** [comment]
Looking at this https://github.com/golang/go/wiki/Modules#semantic-import-versioning it seems that we should make a new `v0.3` package in the root of the repo and implement the `v0.3` client there.

Do you agree?

**Comment by tamccall** [comment]
@nukosuke should we just start on a v0.3 branch to merge into while we are trying to setup the current patterns of all of this?

**Comment by nukosuke** [comment]
@tamccall 

It's fine to use master for developing v0.3.

Also, I don't think that we need v0.2 branch specially because we would apply very few patches to it.
I'll checkout v0.2.0 tag and cherry-pick the hotfixes to master on each occasion.

**Comment by nukosuke** [comment]
After PRs above are merged, exported http methods (`Get`, `Post`, `Put`, `Delete`) can be removed (#102).
