### ISSUE TITLE
Add ticket creation support

### ISSUE THREAD

**Issue by tamccall** [nukosuke/go-zendesk#92]
for the go-zendesk client to be usefult to the majority of zendesk integrations it will need to at least support ticket creation.

https://developer.zendesk.com/rest_api/docs/support/tickets

you can see in the top two python libraries they dedicate a significant amount of the README just showing how to create tickets.

- https://github.com/facetoe/zenpy
- https://github.com/fprimex/zdesk

should add the ability to create tickets to this library to make it more generally useful and update the readme to show how to do it.

**Comment by tamccall** [comment]
If we are setting goals for `0.3.0` we may want to consider the greater go zendesk landscape.

[This](https://github.com/MEDIGO/go-zendesk) seems to be the top zendesk client for go right now. Might be worth trying to get parity with it on the ticket api.

**Comment by nukosuke** [comment]
I think we should tackle context problem (#70) before adding new support, otherwise numerous methods without context make more difficult to achieve this issue.

**Comment by tamccall** [comment]
fair point

**Comment by tamccall** [comment]
@nukosuke can this be closed?

**Comment by nukosuke** [comment]
yeah, it's done. Thanks!
