### ISSUE TITLE
contact zendesk to get added to the clients list

### ISSUE THREAD

**Issue by tamccall** [nukosuke/go-zendesk#94]
https://developer.zendesk.com/rest_api/docs/api-clients/introduction

**Comment by gdm85** [comment]
I agree, I have checked the other available Go client libraries and this seems the best.

**Comment by nukosuke** [comment]
I sent an email to them.
Thank you for your feedback.

**Comment by tamccall** [comment]
@nukosuke is there any update for this issue?

**Comment by nukosuke** [comment]
@tamccall 

Umm, I know my English is broken.
Do you think that they understand what I meant?

—-

Hi, I'm nukosuke.

We developed Zendesk API library for Go and want to introduce it.
https://github.com/nukosuke/go-zendesk

Could you check and list it to your API client page?
https://developer.zendesk.com/rest_api/docs/api-clients/introduction

Regards,
nukosuke


—-

Hello Nukosuke,

Thanks for getting in touch with the Zendesk Customer Advocacy team, and apologies for the delayed response; we've been dealing with a high volume of tickets lately.

Thank you for your interest in Zendesk! To learn more about our partner programs, please visit www.zendesk.com/partners. To become a partner, please apply online.

If you are interested in our APIs or developing an App, please visit developer.zendesk.com.

Regards,

**Comment by nukosuke** [comment]
I added @tamccall to CC.
The status can be checked on https://support.zendesk.com/hc/ja/requests/4498762.

**Comment by tamccall** [comment]
Since we weren't getting much movement on the original ticket I went ahead and opened up a second ticket https://support.zendesk.com/hc/en-us/requests/4655957# . Let me know if you want to be added to the cc list.

**Comment by tamccall** [comment]
Going to close this zendesk had gotten back to me in my ticket and stated that the are not interested in adding us to the client list at this time.
