### ISSUE TITLE
Support pagination for listing method

### ISSUE THREAD

**Issue by nukosuke** [nukosuke/go-zendesk#95]
All `Get~s()` methods should take page number as an argument which is used for the query string.

https://develop.zendesk.com/hc/en-us/articles/360001068607

**Comment by nukosuke** [comment]
We should make decision for https://github.com/nukosuke/go-zendesk/pull/96#discussion_r277490538 before working on it.

**Comment by tamccall** [comment]
Am i correct in saying that the groups api does not seem to have any options that we need to support?

https://developer.zendesk.com/rest_api/docs/support/groups#list-groups

**Comment by nukosuke** [comment]
Yeah, I think only brand and trigger support pagination feature.

**Comment by tamccall** [comment]
Well i added this guy here https://github.com/nukosuke/go-zendesk/blob/master/zendesk/user.go#L66-L74

I'm trying to figure out what is left to do.

**Comment by tamccall** [comment]
did an audit today and i think these are the ones that have been implemented that are missing.

- [ ] groups
- [ ] ticket fields
- [ ] users
- [ ] user fields

let me know if i missed anything

**Comment by nukosuke** [comment]
Thank you.
I added this issue to the v0.5.0 milestone.
We would support pagination of all resources in the next minor version.

**Comment by tamccall** [comment]
Looks like the groups api doesn't support pagination so we are probably good on that front
https://developer.zendesk.com/rest_api/docs/support/groups#list-groups

**Comment by tamccall** [comment]
Ticket fields also seems to not support it.

https://developer.zendesk.com/rest_api/docs/support/ticket_fields#list-ticket-fields

**Comment by tamccall** [comment]
Users api also does not seem to support pagination.

https://developer.zendesk.com/rest_api/docs/support/users#list-users

**Comment by tamccall** [comment]
If my review on the api docs is correct i think the only one we have left to update is the list user fields API. https://developer.zendesk.com/rest_api/docs/support/user_fields

I'll get started on that.

**Comment by tamccall** [comment]
i think this issue has been resolved at this point closing.
